remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Your Name
logo: /images/profilepic.jpeg"
theme: jekyll-theme-minimal
description: Sudarshana Zagade â€“ Web Developer | MCA Student
